---
language: python
python: 
  - "2.7"
  - "3.6"

# Use the new container infrastructure
sudo: false

dist: xenial

service:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible 'molecule[docker]'
  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/