- name: bitbucket_backup_repositories | Cloning {{ repo }}
  git:
    repo: "git@bitbucket.org:{{ bitbucket_workspace }}/{{ repo }}.git"
    dest: "/tmp/git_repos/{{ repo }}"
    version: "{{ bitbucket_git_version }}"
